# Generated by Django 4.2.7 on 2023-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_cover_image_userpostfav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
