# Generated by Django 4.2.7 on 2023-11-30 00:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=['author__name', 'pub_date__month']),
        ),
    ]
