# Generated by Django 4.2.7 on 2023-11-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_user_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
