# Generated by Django 4.2.7 on 2023-11-30 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_profile',
        ),
    ]
