# Generated by Django 4.2.7 on 2023-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_rename_user_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
